
loukis_main():-
	include_sources(),
	reset_index(),
	reset_pawn(),
	reset_khan(),
	initBoard(),
	%ask_initial_pawns_placement(),
	place_pawn(1, 1, 'S1', 2),
	place_pawn(1, 2, 'S2', 2),
	place_pawn(1, 3, 'S3', 2),
	place_pawn(1, 4, 'S4', 2),
	place_pawn(1, 5, 'S5', 2),
	place_pawn(3, 4, 'K', 2),
	place_pawn(6, 1, 'S1', 1),
	place_pawn(6, 2, 'S2', 1),
	place_pawn(6, 3, 'S3', 1),
	place_pawn(6, 4, 'S4', 1),
	place_pawn(6, 5, 'S5', 1),
	place_pawn(6, 6, 'K', 1),
	dynamic_display_active_board(),
	%ask_movement_to_player(1),
	asserta(khan(1, 1)),
	tryToTakeKalista(1, 2, Move),
	print(Move).